// Code generated by protoc-gen-go. DO NOT EDIT.
// source: registration.proto

package registration

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Command struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Server               string   `protobuf:"bytes,2,opt,name=server,proto3" json:"server,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Regex                string   `protobuf:"bytes,4,opt,name=regex,proto3" json:"regex,omitempty"`
	RequireMention       bool     `protobuf:"varint,5,opt,name=requireMention,proto3" json:"requireMention,omitempty"`
	Endpoint             string   `protobuf:"bytes,6,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	Help                 string   `protobuf:"bytes,7,opt,name=help,proto3" json:"help,omitempty"`
	Enabled              bool     `protobuf:"varint,8,opt,name=enabled,proto3" json:"enabled,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Command) Reset()         { *m = Command{} }
func (m *Command) String() string { return proto.CompactTextString(m) }
func (*Command) ProtoMessage()    {}
func (*Command) Descriptor() ([]byte, []int) {
	return fileDescriptor_registration_df11ec03cd296385, []int{0}
}
func (m *Command) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Command.Unmarshal(m, b)
}
func (m *Command) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Command.Marshal(b, m, deterministic)
}
func (dst *Command) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Command.Merge(dst, src)
}
func (m *Command) XXX_Size() int {
	return xxx_messageInfo_Command.Size(m)
}
func (m *Command) XXX_DiscardUnknown() {
	xxx_messageInfo_Command.DiscardUnknown(m)
}

var xxx_messageInfo_Command proto.InternalMessageInfo

func (m *Command) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Command) GetServer() string {
	if m != nil {
		return m.Server
	}
	return ""
}

func (m *Command) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Command) GetRegex() string {
	if m != nil {
		return m.Regex
	}
	return ""
}

func (m *Command) GetRequireMention() bool {
	if m != nil {
		return m.RequireMention
	}
	return false
}

func (m *Command) GetEndpoint() string {
	if m != nil {
		return m.Endpoint
	}
	return ""
}

func (m *Command) GetHelp() string {
	if m != nil {
		return m.Help
	}
	return ""
}

func (m *Command) GetEnabled() bool {
	if m != nil {
		return m.Enabled
	}
	return false
}

type QueryCommandsRequest struct {
	Server               string   `protobuf:"bytes,1,opt,name=server,proto3" json:"server,omitempty"`
	LastId               string   `protobuf:"bytes,2,opt,name=lastId,proto3" json:"lastId,omitempty"`
	PageSize             int32    `protobuf:"varint,3,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryCommandsRequest) Reset()         { *m = QueryCommandsRequest{} }
func (m *QueryCommandsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryCommandsRequest) ProtoMessage()    {}
func (*QueryCommandsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_registration_df11ec03cd296385, []int{1}
}
func (m *QueryCommandsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryCommandsRequest.Unmarshal(m, b)
}
func (m *QueryCommandsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryCommandsRequest.Marshal(b, m, deterministic)
}
func (dst *QueryCommandsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryCommandsRequest.Merge(dst, src)
}
func (m *QueryCommandsRequest) XXX_Size() int {
	return xxx_messageInfo_QueryCommandsRequest.Size(m)
}
func (m *QueryCommandsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryCommandsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryCommandsRequest proto.InternalMessageInfo

func (m *QueryCommandsRequest) GetServer() string {
	if m != nil {
		return m.Server
	}
	return ""
}

func (m *QueryCommandsRequest) GetLastId() string {
	if m != nil {
		return m.LastId
	}
	return ""
}

func (m *QueryCommandsRequest) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

type QueryCommandsReply struct {
	Commands             []*Command `protobuf:"bytes,1,rep,name=Commands,proto3" json:"Commands,omitempty"`
	HasMore              bool       `protobuf:"varint,2,opt,name=hasMore,proto3" json:"hasMore,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *QueryCommandsReply) Reset()         { *m = QueryCommandsReply{} }
func (m *QueryCommandsReply) String() string { return proto.CompactTextString(m) }
func (*QueryCommandsReply) ProtoMessage()    {}
func (*QueryCommandsReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_registration_df11ec03cd296385, []int{2}
}
func (m *QueryCommandsReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryCommandsReply.Unmarshal(m, b)
}
func (m *QueryCommandsReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryCommandsReply.Marshal(b, m, deterministic)
}
func (dst *QueryCommandsReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryCommandsReply.Merge(dst, src)
}
func (m *QueryCommandsReply) XXX_Size() int {
	return xxx_messageInfo_QueryCommandsReply.Size(m)
}
func (m *QueryCommandsReply) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryCommandsReply.DiscardUnknown(m)
}

var xxx_messageInfo_QueryCommandsReply proto.InternalMessageInfo

func (m *QueryCommandsReply) GetCommands() []*Command {
	if m != nil {
		return m.Commands
	}
	return nil
}

func (m *QueryCommandsReply) GetHasMore() bool {
	if m != nil {
		return m.HasMore
	}
	return false
}

type AddCommandRequest struct {
	Command              *Command `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddCommandRequest) Reset()         { *m = AddCommandRequest{} }
func (m *AddCommandRequest) String() string { return proto.CompactTextString(m) }
func (*AddCommandRequest) ProtoMessage()    {}
func (*AddCommandRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_registration_df11ec03cd296385, []int{3}
}
func (m *AddCommandRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddCommandRequest.Unmarshal(m, b)
}
func (m *AddCommandRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddCommandRequest.Marshal(b, m, deterministic)
}
func (dst *AddCommandRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddCommandRequest.Merge(dst, src)
}
func (m *AddCommandRequest) XXX_Size() int {
	return xxx_messageInfo_AddCommandRequest.Size(m)
}
func (m *AddCommandRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddCommandRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddCommandRequest proto.InternalMessageInfo

func (m *AddCommandRequest) GetCommand() *Command {
	if m != nil {
		return m.Command
	}
	return nil
}

type AddCommandReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddCommandReply) Reset()         { *m = AddCommandReply{} }
func (m *AddCommandReply) String() string { return proto.CompactTextString(m) }
func (*AddCommandReply) ProtoMessage()    {}
func (*AddCommandReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_registration_df11ec03cd296385, []int{4}
}
func (m *AddCommandReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddCommandReply.Unmarshal(m, b)
}
func (m *AddCommandReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddCommandReply.Marshal(b, m, deterministic)
}
func (dst *AddCommandReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddCommandReply.Merge(dst, src)
}
func (m *AddCommandReply) XXX_Size() int {
	return xxx_messageInfo_AddCommandReply.Size(m)
}
func (m *AddCommandReply) XXX_DiscardUnknown() {
	xxx_messageInfo_AddCommandReply.DiscardUnknown(m)
}

var xxx_messageInfo_AddCommandReply proto.InternalMessageInfo

type DisableCommandRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DisableCommandRequest) Reset()         { *m = DisableCommandRequest{} }
func (m *DisableCommandRequest) String() string { return proto.CompactTextString(m) }
func (*DisableCommandRequest) ProtoMessage()    {}
func (*DisableCommandRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_registration_df11ec03cd296385, []int{5}
}
func (m *DisableCommandRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DisableCommandRequest.Unmarshal(m, b)
}
func (m *DisableCommandRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DisableCommandRequest.Marshal(b, m, deterministic)
}
func (dst *DisableCommandRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DisableCommandRequest.Merge(dst, src)
}
func (m *DisableCommandRequest) XXX_Size() int {
	return xxx_messageInfo_DisableCommandRequest.Size(m)
}
func (m *DisableCommandRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DisableCommandRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DisableCommandRequest proto.InternalMessageInfo

func (m *DisableCommandRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type DisableCommandReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DisableCommandReply) Reset()         { *m = DisableCommandReply{} }
func (m *DisableCommandReply) String() string { return proto.CompactTextString(m) }
func (*DisableCommandReply) ProtoMessage()    {}
func (*DisableCommandReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_registration_df11ec03cd296385, []int{6}
}
func (m *DisableCommandReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DisableCommandReply.Unmarshal(m, b)
}
func (m *DisableCommandReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DisableCommandReply.Marshal(b, m, deterministic)
}
func (dst *DisableCommandReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DisableCommandReply.Merge(dst, src)
}
func (m *DisableCommandReply) XXX_Size() int {
	return xxx_messageInfo_DisableCommandReply.Size(m)
}
func (m *DisableCommandReply) XXX_DiscardUnknown() {
	xxx_messageInfo_DisableCommandReply.DiscardUnknown(m)
}

var xxx_messageInfo_DisableCommandReply proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Command)(nil), "registration.Command")
	proto.RegisterType((*QueryCommandsRequest)(nil), "registration.QueryCommandsRequest")
	proto.RegisterType((*QueryCommandsReply)(nil), "registration.QueryCommandsReply")
	proto.RegisterType((*AddCommandRequest)(nil), "registration.AddCommandRequest")
	proto.RegisterType((*AddCommandReply)(nil), "registration.AddCommandReply")
	proto.RegisterType((*DisableCommandRequest)(nil), "registration.DisableCommandRequest")
	proto.RegisterType((*DisableCommandReply)(nil), "registration.DisableCommandReply")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// RegistrationClient is the client API for Registration service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RegistrationClient interface {
	AddCommand(ctx context.Context, in *AddCommandRequest, opts ...grpc.CallOption) (*AddCommandReply, error)
	DisableCommand(ctx context.Context, in *DisableCommandRequest, opts ...grpc.CallOption) (*DisableCommandReply, error)
	QueryCommands(ctx context.Context, in *QueryCommandsRequest, opts ...grpc.CallOption) (*QueryCommandsReply, error)
}

type registrationClient struct {
	cc *grpc.ClientConn
}

func NewRegistrationClient(cc *grpc.ClientConn) RegistrationClient {
	return &registrationClient{cc}
}

func (c *registrationClient) AddCommand(ctx context.Context, in *AddCommandRequest, opts ...grpc.CallOption) (*AddCommandReply, error) {
	out := new(AddCommandReply)
	err := c.cc.Invoke(ctx, "/registration.Registration/AddCommand", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *registrationClient) DisableCommand(ctx context.Context, in *DisableCommandRequest, opts ...grpc.CallOption) (*DisableCommandReply, error) {
	out := new(DisableCommandReply)
	err := c.cc.Invoke(ctx, "/registration.Registration/DisableCommand", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *registrationClient) QueryCommands(ctx context.Context, in *QueryCommandsRequest, opts ...grpc.CallOption) (*QueryCommandsReply, error) {
	out := new(QueryCommandsReply)
	err := c.cc.Invoke(ctx, "/registration.Registration/QueryCommands", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RegistrationServer is the server API for Registration service.
type RegistrationServer interface {
	AddCommand(context.Context, *AddCommandRequest) (*AddCommandReply, error)
	DisableCommand(context.Context, *DisableCommandRequest) (*DisableCommandReply, error)
	QueryCommands(context.Context, *QueryCommandsRequest) (*QueryCommandsReply, error)
}

func RegisterRegistrationServer(s *grpc.Server, srv RegistrationServer) {
	s.RegisterService(&_Registration_serviceDesc, srv)
}

func _Registration_AddCommand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddCommandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistrationServer).AddCommand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/registration.Registration/AddCommand",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistrationServer).AddCommand(ctx, req.(*AddCommandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Registration_DisableCommand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DisableCommandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistrationServer).DisableCommand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/registration.Registration/DisableCommand",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistrationServer).DisableCommand(ctx, req.(*DisableCommandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Registration_QueryCommands_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryCommandsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistrationServer).QueryCommands(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/registration.Registration/QueryCommands",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistrationServer).QueryCommands(ctx, req.(*QueryCommandsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Registration_serviceDesc = grpc.ServiceDesc{
	ServiceName: "registration.Registration",
	HandlerType: (*RegistrationServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddCommand",
			Handler:    _Registration_AddCommand_Handler,
		},
		{
			MethodName: "DisableCommand",
			Handler:    _Registration_DisableCommand_Handler,
		},
		{
			MethodName: "QueryCommands",
			Handler:    _Registration_QueryCommands_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "registration.proto",
}

func init() { proto.RegisterFile("registration.proto", fileDescriptor_registration_df11ec03cd296385) }

var fileDescriptor_registration_df11ec03cd296385 = []byte{
	// 391 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x53, 0xc1, 0x0e, 0xd2, 0x40,
	0x14, 0xb4, 0x05, 0xda, 0xfa, 0x44, 0x0c, 0x4f, 0x20, 0x9b, 0x26, 0xc6, 0xba, 0x26, 0xca, 0x09,
	0x23, 0x7e, 0x81, 0x91, 0x8b, 0x07, 0x4c, 0xac, 0x07, 0x13, 0x6f, 0x8b, 0xfb, 0x02, 0x9b, 0x94,
	0xb6, 0x6c, 0x8b, 0xb1, 0xfe, 0x86, 0xdf, 0xe5, 0x3f, 0x99, 0x6e, 0x5b, 0x6c, 0x2b, 0x70, 0xdb,
	0x19, 0xe6, 0xcd, 0xbc, 0xd9, 0xa5, 0x80, 0x9a, 0xf6, 0x2a, 0xcb, 0xb5, 0xc8, 0x55, 0x12, 0xaf,
	0x52, 0x9d, 0xe4, 0x09, 0x8e, 0xdb, 0x1c, 0xff, 0x63, 0x81, 0xfb, 0x21, 0x39, 0x1e, 0x45, 0x2c,
	0x71, 0x02, 0xb6, 0x92, 0xcc, 0x0a, 0xac, 0xe5, 0xc3, 0xd0, 0x56, 0x12, 0x17, 0xe0, 0x64, 0xa4,
	0x7f, 0x90, 0x66, 0xb6, 0xe1, 0x6a, 0x84, 0x08, 0xc3, 0x58, 0x1c, 0x89, 0x0d, 0x0c, 0x6b, 0xce,
	0x38, 0x83, 0x91, 0xa6, 0x3d, 0xfd, 0x64, 0x43, 0x43, 0x56, 0x00, 0x5f, 0xc1, 0x44, 0xd3, 0xe9,
	0xac, 0x34, 0x6d, 0x29, 0x2e, 0xf3, 0xd8, 0x28, 0xb0, 0x96, 0x5e, 0xd8, 0x63, 0xd1, 0x07, 0x8f,
	0x62, 0x99, 0x26, 0x2a, 0xce, 0x99, 0x63, 0x0c, 0x2e, 0xb8, 0x4c, 0x3b, 0x50, 0x94, 0x32, 0xb7,
	0x4a, 0x2b, 0xcf, 0xc8, 0xc0, 0xa5, 0x58, 0xec, 0x22, 0x92, 0xcc, 0x33, 0x86, 0x0d, 0xe4, 0x3b,
	0x98, 0x7d, 0x3e, 0x93, 0x2e, 0xea, 0x4e, 0x59, 0x48, 0xa7, 0x33, 0x65, 0x79, 0xab, 0x8b, 0xd5,
	0xe9, 0xb2, 0x00, 0x27, 0x12, 0x59, 0xfe, 0x51, 0x36, 0x1d, 0x2b, 0x54, 0x6e, 0x94, 0x8a, 0x3d,
	0x7d, 0x51, 0xbf, 0xaa, 0x9e, 0xa3, 0xf0, 0x82, 0xb9, 0x00, 0xec, 0x65, 0xa4, 0x51, 0x81, 0x6f,
	0xc1, 0x6b, 0x08, 0x66, 0x05, 0x83, 0xe5, 0xa3, 0xf5, 0x7c, 0xd5, 0xb9, 0xfe, 0xfa, 0xd7, 0xf0,
	0x22, 0x2b, 0x6b, 0x1c, 0x44, 0xb6, 0x4d, 0x34, 0x99, 0x74, 0x2f, 0x6c, 0x20, 0xdf, 0xc0, 0xf4,
	0xbd, 0x94, 0xcd, 0x44, 0xdd, 0xe1, 0x0d, 0xb8, 0xdf, 0x2b, 0xc6, 0x94, 0xb8, 0x19, 0xd0, 0xa8,
	0xf8, 0x14, 0x9e, 0xb4, 0x5d, 0xd2, 0xa8, 0xe0, 0xaf, 0x61, 0xbe, 0x51, 0x59, 0x79, 0x57, 0x3d,
	0xf3, 0xde, 0xe3, 0xf3, 0x39, 0x3c, 0xed, 0x0b, 0xd3, 0xa8, 0x58, 0xff, 0xb6, 0x61, 0x1c, 0xb6,
	0x42, 0xf1, 0x13, 0xc0, 0xbf, 0x0c, 0x7c, 0xde, 0xdd, 0xe8, 0xbf, 0x0e, 0xfe, 0xb3, 0xdb, 0x82,
	0x72, 0xbd, 0x07, 0xf8, 0x0d, 0x26, 0xdd, 0x5c, 0x7c, 0xd9, 0x1d, 0xb9, 0xba, 0xbe, 0xff, 0xe2,
	0xbe, 0xa8, 0xf2, 0xfe, 0x0a, 0x8f, 0x3b, 0x0f, 0x87, 0xbc, 0x3b, 0x75, 0xed, 0x9f, 0xe3, 0x07,
	0x77, 0x35, 0xc6, 0x78, 0xe7, 0x98, 0x4f, 0xeb, 0xdd, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0xd8,
	0x8c, 0x13, 0xed, 0x70, 0x03, 0x00, 0x00,
}
