// Code generated by protoc-gen-go. DO NOT EDIT.
// source: processing.proto

package processing

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ReplyReceived struct {
	Id                   string   `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReplyReceived) Reset()         { *m = ReplyReceived{} }
func (m *ReplyReceived) String() string { return proto.CompactTextString(m) }
func (*ReplyReceived) ProtoMessage()    {}
func (*ReplyReceived) Descriptor() ([]byte, []int) {
	return fileDescriptor_processing_552c1783aa3575bb, []int{0}
}
func (m *ReplyReceived) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplyReceived.Unmarshal(m, b)
}
func (m *ReplyReceived) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplyReceived.Marshal(b, m, deterministic)
}
func (dst *ReplyReceived) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplyReceived.Merge(dst, src)
}
func (m *ReplyReceived) XXX_Size() int {
	return xxx_messageInfo_ReplyReceived.Size(m)
}
func (m *ReplyReceived) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplyReceived.DiscardUnknown(m)
}

var xxx_messageInfo_ReplyReceived proto.InternalMessageInfo

func (m *ReplyReceived) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type MessagesRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessagesRequest) Reset()         { *m = MessagesRequest{} }
func (m *MessagesRequest) String() string { return proto.CompactTextString(m) }
func (*MessagesRequest) ProtoMessage()    {}
func (*MessagesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_processing_552c1783aa3575bb, []int{1}
}
func (m *MessagesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessagesRequest.Unmarshal(m, b)
}
func (m *MessagesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessagesRequest.Marshal(b, m, deterministic)
}
func (dst *MessagesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessagesRequest.Merge(dst, src)
}
func (m *MessagesRequest) XXX_Size() int {
	return xxx_messageInfo_MessagesRequest.Size(m)
}
func (m *MessagesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MessagesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MessagesRequest proto.InternalMessageInfo

func (m *MessagesRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type Reply struct {
	Id                   string     `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Messages             []*Message `protobuf:"bytes,2,rep,name=messages,proto3" json:"messages,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Reply) Reset()         { *m = Reply{} }
func (m *Reply) String() string { return proto.CompactTextString(m) }
func (*Reply) ProtoMessage()    {}
func (*Reply) Descriptor() ([]byte, []int) {
	return fileDescriptor_processing_552c1783aa3575bb, []int{2}
}
func (m *Reply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Reply.Unmarshal(m, b)
}
func (m *Reply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Reply.Marshal(b, m, deterministic)
}
func (dst *Reply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Reply.Merge(dst, src)
}
func (m *Reply) XXX_Size() int {
	return xxx_messageInfo_Reply.Size(m)
}
func (m *Reply) XXX_DiscardUnknown() {
	xxx_messageInfo_Reply.DiscardUnknown(m)
}

var xxx_messageInfo_Reply proto.InternalMessageInfo

func (m *Reply) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Reply) GetMessages() []*Message {
	if m != nil {
		return m.Messages
	}
	return nil
}

type Message struct {
	Content              string   `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	Embed                *Embed   `protobuf:"bytes,2,opt,name=embed,proto3" json:"embed,omitempty"`
	Tts                  bool     `protobuf:"varint,3,opt,name=tts,proto3" json:"tts,omitempty"`
	Files                []*File  `protobuf:"bytes,4,rep,name=files,proto3" json:"files,omitempty"`
	IsPrivateMessage     bool     `protobuf:"varint,5,opt,name=isPrivateMessage,proto3" json:"isPrivateMessage,omitempty"`
	IsRedirect           bool     `protobuf:"varint,6,opt,name=isRedirect,proto3" json:"isRedirect,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_processing_552c1783aa3575bb, []int{3}
}
func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (dst *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(dst, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *Message) GetEmbed() *Embed {
	if m != nil {
		return m.Embed
	}
	return nil
}

func (m *Message) GetTts() bool {
	if m != nil {
		return m.Tts
	}
	return false
}

func (m *Message) GetFiles() []*File {
	if m != nil {
		return m.Files
	}
	return nil
}

func (m *Message) GetIsPrivateMessage() bool {
	if m != nil {
		return m.IsPrivateMessage
	}
	return false
}

func (m *Message) GetIsRedirect() bool {
	if m != nil {
		return m.IsRedirect
	}
	return false
}

type EmbedFooter struct {
	Text                 string   `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	IconUrl              string   `protobuf:"bytes,2,opt,name=iconUrl,proto3" json:"iconUrl,omitempty"`
	ProxyIconUrl         string   `protobuf:"bytes,3,opt,name=proxyIconUrl,proto3" json:"proxyIconUrl,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmbedFooter) Reset()         { *m = EmbedFooter{} }
func (m *EmbedFooter) String() string { return proto.CompactTextString(m) }
func (*EmbedFooter) ProtoMessage()    {}
func (*EmbedFooter) Descriptor() ([]byte, []int) {
	return fileDescriptor_processing_552c1783aa3575bb, []int{4}
}
func (m *EmbedFooter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmbedFooter.Unmarshal(m, b)
}
func (m *EmbedFooter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmbedFooter.Marshal(b, m, deterministic)
}
func (dst *EmbedFooter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmbedFooter.Merge(dst, src)
}
func (m *EmbedFooter) XXX_Size() int {
	return xxx_messageInfo_EmbedFooter.Size(m)
}
func (m *EmbedFooter) XXX_DiscardUnknown() {
	xxx_messageInfo_EmbedFooter.DiscardUnknown(m)
}

var xxx_messageInfo_EmbedFooter proto.InternalMessageInfo

func (m *EmbedFooter) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *EmbedFooter) GetIconUrl() string {
	if m != nil {
		return m.IconUrl
	}
	return ""
}

func (m *EmbedFooter) GetProxyIconUrl() string {
	if m != nil {
		return m.ProxyIconUrl
	}
	return ""
}

type EmbedImage struct {
	Url                  string   `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	ProxyUrl             string   `protobuf:"bytes,2,opt,name=proxyUrl,proto3" json:"proxyUrl,omitempty"`
	Width                int32    `protobuf:"varint,3,opt,name=width,proto3" json:"width,omitempty"`
	Height               int32    `protobuf:"varint,4,opt,name=height,proto3" json:"height,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmbedImage) Reset()         { *m = EmbedImage{} }
func (m *EmbedImage) String() string { return proto.CompactTextString(m) }
func (*EmbedImage) ProtoMessage()    {}
func (*EmbedImage) Descriptor() ([]byte, []int) {
	return fileDescriptor_processing_552c1783aa3575bb, []int{5}
}
func (m *EmbedImage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmbedImage.Unmarshal(m, b)
}
func (m *EmbedImage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmbedImage.Marshal(b, m, deterministic)
}
func (dst *EmbedImage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmbedImage.Merge(dst, src)
}
func (m *EmbedImage) XXX_Size() int {
	return xxx_messageInfo_EmbedImage.Size(m)
}
func (m *EmbedImage) XXX_DiscardUnknown() {
	xxx_messageInfo_EmbedImage.DiscardUnknown(m)
}

var xxx_messageInfo_EmbedImage proto.InternalMessageInfo

func (m *EmbedImage) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *EmbedImage) GetProxyUrl() string {
	if m != nil {
		return m.ProxyUrl
	}
	return ""
}

func (m *EmbedImage) GetWidth() int32 {
	if m != nil {
		return m.Width
	}
	return 0
}

func (m *EmbedImage) GetHeight() int32 {
	if m != nil {
		return m.Height
	}
	return 0
}

type EmbedThumbnail struct {
	Url                  string   `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	ProxyUrl             string   `protobuf:"bytes,2,opt,name=proxyUrl,proto3" json:"proxyUrl,omitempty"`
	Width                int32    `protobuf:"varint,3,opt,name=width,proto3" json:"width,omitempty"`
	Height               int32    `protobuf:"varint,4,opt,name=height,proto3" json:"height,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmbedThumbnail) Reset()         { *m = EmbedThumbnail{} }
func (m *EmbedThumbnail) String() string { return proto.CompactTextString(m) }
func (*EmbedThumbnail) ProtoMessage()    {}
func (*EmbedThumbnail) Descriptor() ([]byte, []int) {
	return fileDescriptor_processing_552c1783aa3575bb, []int{6}
}
func (m *EmbedThumbnail) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmbedThumbnail.Unmarshal(m, b)
}
func (m *EmbedThumbnail) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmbedThumbnail.Marshal(b, m, deterministic)
}
func (dst *EmbedThumbnail) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmbedThumbnail.Merge(dst, src)
}
func (m *EmbedThumbnail) XXX_Size() int {
	return xxx_messageInfo_EmbedThumbnail.Size(m)
}
func (m *EmbedThumbnail) XXX_DiscardUnknown() {
	xxx_messageInfo_EmbedThumbnail.DiscardUnknown(m)
}

var xxx_messageInfo_EmbedThumbnail proto.InternalMessageInfo

func (m *EmbedThumbnail) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *EmbedThumbnail) GetProxyUrl() string {
	if m != nil {
		return m.ProxyUrl
	}
	return ""
}

func (m *EmbedThumbnail) GetWidth() int32 {
	if m != nil {
		return m.Width
	}
	return 0
}

func (m *EmbedThumbnail) GetHeight() int32 {
	if m != nil {
		return m.Height
	}
	return 0
}

type EmbedVideo struct {
	Url                  string   `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	ProxyUrl             string   `protobuf:"bytes,2,opt,name=proxyUrl,proto3" json:"proxyUrl,omitempty"`
	Width                int32    `protobuf:"varint,3,opt,name=width,proto3" json:"width,omitempty"`
	Height               int32    `protobuf:"varint,4,opt,name=height,proto3" json:"height,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmbedVideo) Reset()         { *m = EmbedVideo{} }
func (m *EmbedVideo) String() string { return proto.CompactTextString(m) }
func (*EmbedVideo) ProtoMessage()    {}
func (*EmbedVideo) Descriptor() ([]byte, []int) {
	return fileDescriptor_processing_552c1783aa3575bb, []int{7}
}
func (m *EmbedVideo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmbedVideo.Unmarshal(m, b)
}
func (m *EmbedVideo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmbedVideo.Marshal(b, m, deterministic)
}
func (dst *EmbedVideo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmbedVideo.Merge(dst, src)
}
func (m *EmbedVideo) XXX_Size() int {
	return xxx_messageInfo_EmbedVideo.Size(m)
}
func (m *EmbedVideo) XXX_DiscardUnknown() {
	xxx_messageInfo_EmbedVideo.DiscardUnknown(m)
}

var xxx_messageInfo_EmbedVideo proto.InternalMessageInfo

func (m *EmbedVideo) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *EmbedVideo) GetProxyUrl() string {
	if m != nil {
		return m.ProxyUrl
	}
	return ""
}

func (m *EmbedVideo) GetWidth() int32 {
	if m != nil {
		return m.Width
	}
	return 0
}

func (m *EmbedVideo) GetHeight() int32 {
	if m != nil {
		return m.Height
	}
	return 0
}

type EmbedProvider struct {
	Url                  string   `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmbedProvider) Reset()         { *m = EmbedProvider{} }
func (m *EmbedProvider) String() string { return proto.CompactTextString(m) }
func (*EmbedProvider) ProtoMessage()    {}
func (*EmbedProvider) Descriptor() ([]byte, []int) {
	return fileDescriptor_processing_552c1783aa3575bb, []int{8}
}
func (m *EmbedProvider) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmbedProvider.Unmarshal(m, b)
}
func (m *EmbedProvider) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmbedProvider.Marshal(b, m, deterministic)
}
func (dst *EmbedProvider) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmbedProvider.Merge(dst, src)
}
func (m *EmbedProvider) XXX_Size() int {
	return xxx_messageInfo_EmbedProvider.Size(m)
}
func (m *EmbedProvider) XXX_DiscardUnknown() {
	xxx_messageInfo_EmbedProvider.DiscardUnknown(m)
}

var xxx_messageInfo_EmbedProvider proto.InternalMessageInfo

func (m *EmbedProvider) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *EmbedProvider) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type EmbedAuthor struct {
	Url                  string   `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	IconUrl              string   `protobuf:"bytes,3,opt,name=iconUrl,proto3" json:"iconUrl,omitempty"`
	ProxyIconUrl         string   `protobuf:"bytes,4,opt,name=proxyIconUrl,proto3" json:"proxyIconUrl,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmbedAuthor) Reset()         { *m = EmbedAuthor{} }
func (m *EmbedAuthor) String() string { return proto.CompactTextString(m) }
func (*EmbedAuthor) ProtoMessage()    {}
func (*EmbedAuthor) Descriptor() ([]byte, []int) {
	return fileDescriptor_processing_552c1783aa3575bb, []int{9}
}
func (m *EmbedAuthor) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmbedAuthor.Unmarshal(m, b)
}
func (m *EmbedAuthor) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmbedAuthor.Marshal(b, m, deterministic)
}
func (dst *EmbedAuthor) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmbedAuthor.Merge(dst, src)
}
func (m *EmbedAuthor) XXX_Size() int {
	return xxx_messageInfo_EmbedAuthor.Size(m)
}
func (m *EmbedAuthor) XXX_DiscardUnknown() {
	xxx_messageInfo_EmbedAuthor.DiscardUnknown(m)
}

var xxx_messageInfo_EmbedAuthor proto.InternalMessageInfo

func (m *EmbedAuthor) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *EmbedAuthor) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *EmbedAuthor) GetIconUrl() string {
	if m != nil {
		return m.IconUrl
	}
	return ""
}

func (m *EmbedAuthor) GetProxyIconUrl() string {
	if m != nil {
		return m.ProxyIconUrl
	}
	return ""
}

type EmbedField struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Inline               bool     `protobuf:"varint,3,opt,name=inline,proto3" json:"inline,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmbedField) Reset()         { *m = EmbedField{} }
func (m *EmbedField) String() string { return proto.CompactTextString(m) }
func (*EmbedField) ProtoMessage()    {}
func (*EmbedField) Descriptor() ([]byte, []int) {
	return fileDescriptor_processing_552c1783aa3575bb, []int{10}
}
func (m *EmbedField) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmbedField.Unmarshal(m, b)
}
func (m *EmbedField) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmbedField.Marshal(b, m, deterministic)
}
func (dst *EmbedField) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmbedField.Merge(dst, src)
}
func (m *EmbedField) XXX_Size() int {
	return xxx_messageInfo_EmbedField.Size(m)
}
func (m *EmbedField) XXX_DiscardUnknown() {
	xxx_messageInfo_EmbedField.DiscardUnknown(m)
}

var xxx_messageInfo_EmbedField proto.InternalMessageInfo

func (m *EmbedField) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *EmbedField) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *EmbedField) GetInline() bool {
	if m != nil {
		return m.Inline
	}
	return false
}

type Embed struct {
	Url                  string          `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Type                 string          `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Title                string          `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Description          string          `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Timestamp            string          `protobuf:"bytes,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Color                int32           `protobuf:"varint,6,opt,name=color,proto3" json:"color,omitempty"`
	Footer               *EmbedFooter    `protobuf:"bytes,7,opt,name=footer,proto3" json:"footer,omitempty"`
	Image                *EmbedImage     `protobuf:"bytes,8,opt,name=image,proto3" json:"image,omitempty"`
	Thumbnail            *EmbedThumbnail `protobuf:"bytes,9,opt,name=thumbnail,proto3" json:"thumbnail,omitempty"`
	Video                *EmbedVideo     `protobuf:"bytes,10,opt,name=video,proto3" json:"video,omitempty"`
	Provider             *EmbedProvider  `protobuf:"bytes,11,opt,name=provider,proto3" json:"provider,omitempty"`
	Author               *EmbedAuthor    `protobuf:"bytes,12,opt,name=author,proto3" json:"author,omitempty"`
	Fields               []*EmbedField   `protobuf:"bytes,13,rep,name=fields,proto3" json:"fields,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Embed) Reset()         { *m = Embed{} }
func (m *Embed) String() string { return proto.CompactTextString(m) }
func (*Embed) ProtoMessage()    {}
func (*Embed) Descriptor() ([]byte, []int) {
	return fileDescriptor_processing_552c1783aa3575bb, []int{11}
}
func (m *Embed) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Embed.Unmarshal(m, b)
}
func (m *Embed) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Embed.Marshal(b, m, deterministic)
}
func (dst *Embed) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Embed.Merge(dst, src)
}
func (m *Embed) XXX_Size() int {
	return xxx_messageInfo_Embed.Size(m)
}
func (m *Embed) XXX_DiscardUnknown() {
	xxx_messageInfo_Embed.DiscardUnknown(m)
}

var xxx_messageInfo_Embed proto.InternalMessageInfo

func (m *Embed) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *Embed) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Embed) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Embed) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Embed) GetTimestamp() string {
	if m != nil {
		return m.Timestamp
	}
	return ""
}

func (m *Embed) GetColor() int32 {
	if m != nil {
		return m.Color
	}
	return 0
}

func (m *Embed) GetFooter() *EmbedFooter {
	if m != nil {
		return m.Footer
	}
	return nil
}

func (m *Embed) GetImage() *EmbedImage {
	if m != nil {
		return m.Image
	}
	return nil
}

func (m *Embed) GetThumbnail() *EmbedThumbnail {
	if m != nil {
		return m.Thumbnail
	}
	return nil
}

func (m *Embed) GetVideo() *EmbedVideo {
	if m != nil {
		return m.Video
	}
	return nil
}

func (m *Embed) GetProvider() *EmbedProvider {
	if m != nil {
		return m.Provider
	}
	return nil
}

func (m *Embed) GetAuthor() *EmbedAuthor {
	if m != nil {
		return m.Author
	}
	return nil
}

func (m *Embed) GetFields() []*EmbedField {
	if m != nil {
		return m.Fields
	}
	return nil
}

type File struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ContentType          string   `protobuf:"bytes,2,opt,name=contentType,proto3" json:"contentType,omitempty"`
	Bytes                []byte   `protobuf:"bytes,3,opt,name=bytes,proto3" json:"bytes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *File) Reset()         { *m = File{} }
func (m *File) String() string { return proto.CompactTextString(m) }
func (*File) ProtoMessage()    {}
func (*File) Descriptor() ([]byte, []int) {
	return fileDescriptor_processing_552c1783aa3575bb, []int{12}
}
func (m *File) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_File.Unmarshal(m, b)
}
func (m *File) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_File.Marshal(b, m, deterministic)
}
func (dst *File) XXX_Merge(src proto.Message) {
	xxx_messageInfo_File.Merge(dst, src)
}
func (m *File) XXX_Size() int {
	return xxx_messageInfo_File.Size(m)
}
func (m *File) XXX_DiscardUnknown() {
	xxx_messageInfo_File.DiscardUnknown(m)
}

var xxx_messageInfo_File proto.InternalMessageInfo

func (m *File) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *File) GetContentType() string {
	if m != nil {
		return m.ContentType
	}
	return ""
}

func (m *File) GetBytes() []byte {
	if m != nil {
		return m.Bytes
	}
	return nil
}

func init() {
	proto.RegisterType((*ReplyReceived)(nil), "processing.ReplyReceived")
	proto.RegisterType((*MessagesRequest)(nil), "processing.MessagesRequest")
	proto.RegisterType((*Reply)(nil), "processing.Reply")
	proto.RegisterType((*Message)(nil), "processing.Message")
	proto.RegisterType((*EmbedFooter)(nil), "processing.EmbedFooter")
	proto.RegisterType((*EmbedImage)(nil), "processing.EmbedImage")
	proto.RegisterType((*EmbedThumbnail)(nil), "processing.EmbedThumbnail")
	proto.RegisterType((*EmbedVideo)(nil), "processing.EmbedVideo")
	proto.RegisterType((*EmbedProvider)(nil), "processing.EmbedProvider")
	proto.RegisterType((*EmbedAuthor)(nil), "processing.EmbedAuthor")
	proto.RegisterType((*EmbedField)(nil), "processing.EmbedField")
	proto.RegisterType((*Embed)(nil), "processing.Embed")
	proto.RegisterType((*File)(nil), "processing.File")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ProcessingClient is the client API for Processing service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ProcessingClient interface {
	Messages(ctx context.Context, in *MessagesRequest, opts ...grpc.CallOption) (*Reply, error)
}

type processingClient struct {
	cc *grpc.ClientConn
}

func NewProcessingClient(cc *grpc.ClientConn) ProcessingClient {
	return &processingClient{cc}
}

func (c *processingClient) Messages(ctx context.Context, in *MessagesRequest, opts ...grpc.CallOption) (*Reply, error) {
	out := new(Reply)
	err := c.cc.Invoke(ctx, "/processing.Processing/Messages", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProcessingServer is the server API for Processing service.
type ProcessingServer interface {
	Messages(context.Context, *MessagesRequest) (*Reply, error)
}

func RegisterProcessingServer(s *grpc.Server, srv ProcessingServer) {
	s.RegisterService(&_Processing_serviceDesc, srv)
}

func _Processing_Messages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MessagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProcessingServer).Messages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/processing.Processing/Messages",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProcessingServer).Messages(ctx, req.(*MessagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Processing_serviceDesc = grpc.ServiceDesc{
	ServiceName: "processing.Processing",
	HandlerType: (*ProcessingServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Messages",
			Handler:    _Processing_Messages_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "processing.proto",
}

func init() { proto.RegisterFile("processing.proto", fileDescriptor_processing_552c1783aa3575bb) }

var fileDescriptor_processing_552c1783aa3575bb = []byte{
	// 683 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x55, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0x25, 0x1f, 0x4e, 0x93, 0x49, 0x5b, 0xc2, 0x52, 0x95, 0xa5, 0x20, 0x08, 0x3e, 0x40, 0x84,
	0x50, 0x2b, 0x15, 0x55, 0xe2, 0xc0, 0x85, 0x43, 0x2b, 0x82, 0x04, 0xaa, 0x56, 0x85, 0x2b, 0x72,
	0xec, 0x69, 0xb3, 0x92, 0xed, 0x75, 0xbd, 0x9b, 0xd0, 0xfc, 0x4d, 0x7e, 0x0d, 0x47, 0xb4, 0xe3,
	0xb5, 0xe3, 0xca, 0x29, 0xe2, 0xd2, 0xdb, 0xce, 0xcc, 0x9b, 0x37, 0x33, 0xde, 0x37, 0x6b, 0x18,
	0x65, 0xb9, 0x0a, 0x51, 0x6b, 0x99, 0x5e, 0x1d, 0x66, 0xb9, 0x32, 0x8a, 0xc1, 0xda, 0xe3, 0xbf,
	0x84, 0x1d, 0x81, 0x59, 0xbc, 0x12, 0x18, 0xa2, 0x5c, 0x62, 0xc4, 0x76, 0xa1, 0x3d, 0x8d, 0x78,
	0x6b, 0xdc, 0x9a, 0x0c, 0x44, 0x7b, 0x1a, 0xf9, 0xaf, 0xe0, 0xe1, 0x57, 0xd4, 0x3a, 0xb8, 0x42,
	0x2d, 0xf0, 0x7a, 0x81, 0xda, 0x34, 0x20, 0x9f, 0xc1, 0x23, 0x0e, 0x1b, 0x90, 0x55, 0x40, 0x46,
	0xec, 0x08, 0xfa, 0x89, 0xcb, 0xe5, 0xed, 0x71, 0x67, 0x32, 0x3c, 0x7e, 0x7c, 0x58, 0xeb, 0xc6,
	0xf1, 0x8a, 0x0a, 0xe4, 0xff, 0x6e, 0xc1, 0x96, 0xf3, 0x32, 0x0e, 0x5b, 0xa1, 0x4a, 0x0d, 0xa6,
	0xc6, 0x31, 0x96, 0x26, 0x7b, 0x03, 0x1e, 0x26, 0x33, 0x8c, 0x78, 0x7b, 0xdc, 0x9a, 0x0c, 0x8f,
	0x1f, 0xd5, 0x39, 0x4f, 0x6d, 0x40, 0x14, 0x71, 0x36, 0x82, 0x8e, 0x31, 0x9a, 0x77, 0xc6, 0xad,
	0x49, 0x5f, 0xd8, 0x23, 0x7b, 0x0d, 0xde, 0xa5, 0x8c, 0x51, 0xf3, 0x2e, 0xb5, 0x33, 0xaa, 0xa7,
	0x9e, 0xc9, 0x18, 0x45, 0x11, 0x66, 0x6f, 0x61, 0x24, 0xf5, 0x79, 0x2e, 0x97, 0x81, 0x41, 0xd7,
	0x10, 0xf7, 0x88, 0xa6, 0xe1, 0x67, 0x2f, 0x00, 0xa4, 0x16, 0x18, 0xc9, 0x1c, 0x43, 0xc3, 0x7b,
	0x84, 0xaa, 0x79, 0xfc, 0x9f, 0x30, 0xa4, 0xae, 0xce, 0x94, 0x32, 0x98, 0x33, 0x06, 0x5d, 0x83,
	0x37, 0xe5, 0x50, 0x74, 0xb6, 0xb3, 0xca, 0x50, 0xa5, 0xdf, 0xf3, 0x98, 0x66, 0x1a, 0x88, 0xd2,
	0x64, 0x3e, 0x6c, 0x67, 0xb9, 0xba, 0x59, 0x4d, 0x5d, 0xb8, 0x43, 0xe1, 0x5b, 0x3e, 0x7f, 0x0e,
	0x40, 0x05, 0xa6, 0x89, 0x6d, 0x67, 0x04, 0x9d, 0x45, 0x1e, 0x3b, 0x7a, 0x7b, 0x64, 0x07, 0xd0,
	0x27, 0xfc, 0x9a, 0xbe, 0xb2, 0xd9, 0x1e, 0x78, 0xbf, 0x64, 0x64, 0xe6, 0x44, 0xec, 0x89, 0xc2,
	0x60, 0xfb, 0xd0, 0x9b, 0xa3, 0xbc, 0x9a, 0x1b, 0xde, 0x25, 0xb7, 0xb3, 0xfc, 0x18, 0x76, 0xa9,
	0xd2, 0xc5, 0x7c, 0x91, 0xcc, 0xd2, 0x40, 0xc6, 0xf7, 0x5a, 0xad, 0x9c, 0xeb, 0x87, 0x8c, 0x50,
	0xdd, 0x6b, 0xa5, 0x13, 0xd8, 0xa1, 0x4a, 0xe7, 0xb9, 0x5a, 0xca, 0x08, 0xf3, 0x0d, 0xc5, 0x18,
	0x74, 0xd3, 0x20, 0x41, 0x57, 0x88, 0xce, 0xfe, 0xb5, 0xbb, 0xd9, 0x4f, 0x0b, 0x33, 0x57, 0xff,
	0x99, 0x54, 0xbf, 0xeb, 0xce, 0xbf, 0xef, 0xba, 0xbb, 0xe1, 0xae, 0xbf, 0xb9, 0x6f, 0x72, 0x26,
	0x31, 0x8e, 0x2a, 0xfe, 0x56, 0x8d, 0x7f, 0x0f, 0xbc, 0x65, 0x10, 0x2f, 0xca, 0xa2, 0x85, 0x61,
	0x27, 0x97, 0x69, 0x2c, 0x53, 0x74, 0xdb, 0xe0, 0x2c, 0xff, 0x4f, 0x07, 0xbc, 0xd3, 0x72, 0x59,
	0x9a, 0xdd, 0x9b, 0x55, 0x56, 0x75, 0x6f, 0xcf, 0x96, 0xdd, 0x48, 0x13, 0xa3, 0xeb, 0xbd, 0x30,
	0xd8, 0x18, 0x86, 0x11, 0xea, 0x30, 0x97, 0x99, 0x91, 0x2a, 0x75, 0x8d, 0xd7, 0x5d, 0xec, 0x39,
	0x0c, 0x8c, 0x4c, 0x50, 0x9b, 0x20, 0xc9, 0x68, 0x93, 0x06, 0x62, 0xed, 0xb0, 0xac, 0xa1, 0x8a,
	0x55, 0x4e, 0xdb, 0xe3, 0x89, 0xc2, 0x60, 0x47, 0xd0, 0xbb, 0xa4, 0x9d, 0xe1, 0x5b, 0xb4, 0xe8,
	0x4f, 0x1a, 0x8b, 0x5e, 0xac, 0x94, 0x70, 0x30, 0xf6, 0x0e, 0x3c, 0x69, 0x77, 0x80, 0xf7, 0x09,
	0xbf, 0xdf, 0xc0, 0xd3, 0x86, 0x88, 0x02, 0xc4, 0x3e, 0xc0, 0xc0, 0x94, 0x3a, 0xe6, 0x03, 0xca,
	0x38, 0x68, 0x64, 0x54, 0x4a, 0x17, 0x6b, 0xb0, 0xad, 0x63, 0x65, 0xa2, 0x38, 0xdc, 0x51, 0x87,
	0x14, 0x2b, 0x0a, 0x10, 0x3b, 0x21, 0x99, 0x92, 0xae, 0xf8, 0x90, 0x12, 0x9e, 0x36, 0x12, 0x4a,
	0xe1, 0x89, 0x0a, 0x6a, 0xa7, 0x0f, 0x48, 0x57, 0x7c, 0xfb, 0x8e, 0xe9, 0x0b, 0xd9, 0x09, 0x07,
	0x63, 0x87, 0xd0, 0xbb, 0xb4, 0xaa, 0xd0, 0x7c, 0x87, 0x1e, 0xb7, 0x66, 0x5b, 0x24, 0x1a, 0xe1,
	0x50, 0xbe, 0x80, 0xae, 0x7d, 0xf2, 0x36, 0x8a, 0x68, 0x0c, 0x43, 0xf7, 0xda, 0x5e, 0xac, 0x15,
	0x50, 0x77, 0xd9, 0x2b, 0x9b, 0xad, 0x0c, 0x16, 0xaf, 0xeb, 0xb6, 0x28, 0x8c, 0xe3, 0x2f, 0x00,
	0xe7, 0x55, 0x51, 0xf6, 0x11, 0xfa, 0xe5, 0xbf, 0x83, 0x3d, 0xdb, 0xf0, 0xf2, 0x97, 0x7f, 0x94,
	0x83, 0x5b, 0x4f, 0x38, 0xfd, 0x4b, 0xfc, 0x07, 0xb3, 0x1e, 0xfd, 0xad, 0xde, 0xff, 0x0d, 0x00,
	0x00, 0xff, 0xff, 0xa2, 0x3a, 0x27, 0x43, 0xc1, 0x06, 0x00, 0x00,
}
