language: go
go:
    - 1.11

services:
  - docker

script:
  - make
  - docker build -t $TRAVIS_REPO_SLUG:$TRAVIS_BRANCH .

before_deploy:
  - echo "$DOCKER_PASS" | docker login -u="$DOCKER_USER" --password-stdin

deploy:
  - provider: script
    script:
        - docker push $TRAVIS_REPO_SLUG:$TRAVIS_BRANCH
    skip_cleanup: true
    on:
      branch: dev

  - provider: releases
    api_key: $GITHUB_TOKEN
    file_glob: true
    file: bin/*
    skip_cleanup: true
    on:
      tags: true

  - provider: script
    script:
        - docker tag $TRAVIS_REPO_SLUG:$TRAVIS_BRANCH $TRAVIS_REPO_SLUG:latest
        - docker push $TRAVIS_REPO_SLUG:$TRAVIS_BRANCH
        - docker push $TRAVIS_REPO_SLUG:latest
    skip_cleanup: true
    on:
      tags: true
