language: go

script:
  - go vet ./...
  - go test -v -race ./...

before_deploy:
  - GOARCH=amd64 go build -o bin/$(basename $TRAVIS_REPO_SLUG)-$TRAVIS_TAG ./cmd/...
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file_glob: true
  file: bin/*
  skip_cleanup: true
  on:
    tags: true
