version: '3'
services:
    migrate:
      build: .
      command: -migrate -db "root@cockroachdb:26257"
      depends_on:
        - cockroachdb
    treediagram:
      build: .
      command: -nats "nats:4222" -db "root@cockroachdb:26257"
      ports:
        - "50051:50051"
      environment:
        - TREEDIAGRAM_DISCORD_TOKEN
      depends_on:
        - nats
        - cockroachdb
        - migrate
    nats:
      image: "nats"
    cockroachdb:
      image: cockroachdb/cockroach
      command: start --insecure
      ports:
        - "26257:26257"
        - "8080:8080"
