version: '3'
services:
    #treediagram:
    #  build: .
    #  command: -migrate -nats "nats:4222" -db "root@cockroachdb:26257"
    #  ports:
    #    - "50051:50051"
    #  environment:
    #    - TREEDIAGRAM_DISCORD_TOKEN
    #  depends_on:
    #    - nats
    #    - cockroachdb

    nats:
      image: "nats"
      ports:
        - "4222:4222"

    cockroachdb:
      image: cockroachdb/cockroach
      command: start --insecure
      ports:
        - "26257:26257"
        - "8080:8080"
