version: '3'
services:
    treediagram:
        build: .
        command: -nats "nats:4222" -db "mongo"
        environment:
            - TREEDIAGRAM_DISCORD_TOKEN
        depends_on:
            - nats
            - mongo
    nats:
        image: "nats"
    mongo:
        image: "mongo"

