// Code generated by protoc-gen-go. DO NOT EDIT.
// source: processing.proto

package processingpb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type MessageReplyReceived struct {
	Id                   string   `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessageReplyReceived) Reset()         { *m = MessageReplyReceived{} }
func (m *MessageReplyReceived) String() string { return proto.CompactTextString(m) }
func (*MessageReplyReceived) ProtoMessage()    {}
func (*MessageReplyReceived) Descriptor() ([]byte, []int) {
	return fileDescriptor_processing_41c2f33854a863ab, []int{0}
}
func (m *MessageReplyReceived) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageReplyReceived.Unmarshal(m, b)
}
func (m *MessageReplyReceived) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageReplyReceived.Marshal(b, m, deterministic)
}
func (dst *MessageReplyReceived) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageReplyReceived.Merge(dst, src)
}
func (m *MessageReplyReceived) XXX_Size() int {
	return xxx_messageInfo_MessageReplyReceived.Size(m)
}
func (m *MessageReplyReceived) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageReplyReceived.DiscardUnknown(m)
}

var xxx_messageInfo_MessageReplyReceived proto.InternalMessageInfo

func (m *MessageReplyReceived) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type MessageRequest struct {
	Id                   string    `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Source               string    `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	Bot                  *User     `protobuf:"bytes,3,opt,name=bot,proto3" json:"bot,omitempty"`
	Author               *User     `protobuf:"bytes,4,opt,name=author,proto3" json:"author,omitempty"`
	ChannelId            string    `protobuf:"bytes,5,opt,name=channelId,proto3" json:"channelId,omitempty"`
	ServerId             string    `protobuf:"bytes,6,opt,name=serverId,proto3" json:"serverId,omitempty"`
	Servers              []*Server `protobuf:"bytes,7,rep,name=servers,proto3" json:"servers,omitempty"`
	Mentions             []*User   `protobuf:"bytes,8,rep,name=mentions,proto3" json:"mentions,omitempty"`
	Content              string    `protobuf:"bytes,9,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *MessageRequest) Reset()         { *m = MessageRequest{} }
func (m *MessageRequest) String() string { return proto.CompactTextString(m) }
func (*MessageRequest) ProtoMessage()    {}
func (*MessageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_processing_41c2f33854a863ab, []int{1}
}
func (m *MessageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageRequest.Unmarshal(m, b)
}
func (m *MessageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageRequest.Marshal(b, m, deterministic)
}
func (dst *MessageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageRequest.Merge(dst, src)
}
func (m *MessageRequest) XXX_Size() int {
	return xxx_messageInfo_MessageRequest.Size(m)
}
func (m *MessageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MessageRequest proto.InternalMessageInfo

func (m *MessageRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *MessageRequest) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

func (m *MessageRequest) GetBot() *User {
	if m != nil {
		return m.Bot
	}
	return nil
}

func (m *MessageRequest) GetAuthor() *User {
	if m != nil {
		return m.Author
	}
	return nil
}

func (m *MessageRequest) GetChannelId() string {
	if m != nil {
		return m.ChannelId
	}
	return ""
}

func (m *MessageRequest) GetServerId() string {
	if m != nil {
		return m.ServerId
	}
	return ""
}

func (m *MessageRequest) GetServers() []*Server {
	if m != nil {
		return m.Servers
	}
	return nil
}

func (m *MessageRequest) GetMentions() []*User {
	if m != nil {
		return m.Mentions
	}
	return nil
}

func (m *MessageRequest) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

type User struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Discriminator        string   `protobuf:"bytes,3,opt,name=discriminator,proto3" json:"discriminator,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_processing_41c2f33854a863ab, []int{2}
}
func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (dst *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(dst, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetDiscriminator() string {
	if m != nil {
		return m.Discriminator
	}
	return ""
}

type Server struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Server) Reset()         { *m = Server{} }
func (m *Server) String() string { return proto.CompactTextString(m) }
func (*Server) ProtoMessage()    {}
func (*Server) Descriptor() ([]byte, []int) {
	return fileDescriptor_processing_41c2f33854a863ab, []int{3}
}
func (m *Server) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Server.Unmarshal(m, b)
}
func (m *Server) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Server.Marshal(b, m, deterministic)
}
func (dst *Server) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Server.Merge(dst, src)
}
func (m *Server) XXX_Size() int {
	return xxx_messageInfo_Server.Size(m)
}
func (m *Server) XXX_DiscardUnknown() {
	xxx_messageInfo_Server.DiscardUnknown(m)
}

var xxx_messageInfo_Server proto.InternalMessageInfo

func (m *Server) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Server) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Response struct {
	Messages             []string `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_processing_41c2f33854a863ab, []int{4}
}
func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (dst *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(dst, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetMessages() []string {
	if m != nil {
		return m.Messages
	}
	return nil
}

type SendMessageRequestReply struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendMessageRequestReply) Reset()         { *m = SendMessageRequestReply{} }
func (m *SendMessageRequestReply) String() string { return proto.CompactTextString(m) }
func (*SendMessageRequestReply) ProtoMessage()    {}
func (*SendMessageRequestReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_processing_41c2f33854a863ab, []int{5}
}
func (m *SendMessageRequestReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendMessageRequestReply.Unmarshal(m, b)
}
func (m *SendMessageRequestReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendMessageRequestReply.Marshal(b, m, deterministic)
}
func (dst *SendMessageRequestReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendMessageRequestReply.Merge(dst, src)
}
func (m *SendMessageRequestReply) XXX_Size() int {
	return xxx_messageInfo_SendMessageRequestReply.Size(m)
}
func (m *SendMessageRequestReply) XXX_DiscardUnknown() {
	xxx_messageInfo_SendMessageRequestReply.DiscardUnknown(m)
}

var xxx_messageInfo_SendMessageRequestReply proto.InternalMessageInfo

func (m *SendMessageRequestReply) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type MessageReplyRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessageReplyRequest) Reset()         { *m = MessageReplyRequest{} }
func (m *MessageReplyRequest) String() string { return proto.CompactTextString(m) }
func (*MessageReplyRequest) ProtoMessage()    {}
func (*MessageReplyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_processing_41c2f33854a863ab, []int{6}
}
func (m *MessageReplyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageReplyRequest.Unmarshal(m, b)
}
func (m *MessageReplyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageReplyRequest.Marshal(b, m, deterministic)
}
func (dst *MessageReplyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageReplyRequest.Merge(dst, src)
}
func (m *MessageReplyRequest) XXX_Size() int {
	return xxx_messageInfo_MessageReplyRequest.Size(m)
}
func (m *MessageReplyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageReplyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MessageReplyRequest proto.InternalMessageInfo

func (m *MessageReplyRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type MessageReply struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ProcessingRequestId  string   `protobuf:"bytes,2,opt,name=processingRequestId,proto3" json:"processingRequestId,omitempty"`
	ChannelId            string   `protobuf:"bytes,3,opt,name=channelId,proto3" json:"channelId,omitempty"`
	UserId               string   `protobuf:"bytes,4,opt,name=userId,proto3" json:"userId,omitempty"`
	Content              string   `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	Created              int64    `protobuf:"varint,6,opt,name=created,proto3" json:"created,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessageReply) Reset()         { *m = MessageReply{} }
func (m *MessageReply) String() string { return proto.CompactTextString(m) }
func (*MessageReply) ProtoMessage()    {}
func (*MessageReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_processing_41c2f33854a863ab, []int{7}
}
func (m *MessageReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageReply.Unmarshal(m, b)
}
func (m *MessageReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageReply.Marshal(b, m, deterministic)
}
func (dst *MessageReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageReply.Merge(dst, src)
}
func (m *MessageReply) XXX_Size() int {
	return xxx_messageInfo_MessageReply.Size(m)
}
func (m *MessageReply) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageReply.DiscardUnknown(m)
}

var xxx_messageInfo_MessageReply proto.InternalMessageInfo

func (m *MessageReply) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *MessageReply) GetProcessingRequestId() string {
	if m != nil {
		return m.ProcessingRequestId
	}
	return ""
}

func (m *MessageReply) GetChannelId() string {
	if m != nil {
		return m.ChannelId
	}
	return ""
}

func (m *MessageReply) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *MessageReply) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *MessageReply) GetCreated() int64 {
	if m != nil {
		return m.Created
	}
	return 0
}

type ProcessingRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type                 string   `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	IntentId             string   `protobuf:"bytes,3,opt,name=intentId,proto3" json:"intentId,omitempty"`
	Source               string   `protobuf:"bytes,4,opt,name=source,proto3" json:"source,omitempty"`
	ChannelId            string   `protobuf:"bytes,5,opt,name=channelId,proto3" json:"channelId,omitempty"`
	ServerId             string   `protobuf:"bytes,6,opt,name=serverId,proto3" json:"serverId,omitempty"`
	BotId                string   `protobuf:"bytes,7,opt,name=botId,proto3" json:"botId,omitempty"`
	UserId               string   `protobuf:"bytes,8,opt,name=userId,proto3" json:"userId,omitempty"`
	Created              int64    `protobuf:"varint,9,opt,name=created,proto3" json:"created,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProcessingRequest) Reset()         { *m = ProcessingRequest{} }
func (m *ProcessingRequest) String() string { return proto.CompactTextString(m) }
func (*ProcessingRequest) ProtoMessage()    {}
func (*ProcessingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_processing_41c2f33854a863ab, []int{8}
}
func (m *ProcessingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProcessingRequest.Unmarshal(m, b)
}
func (m *ProcessingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProcessingRequest.Marshal(b, m, deterministic)
}
func (dst *ProcessingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProcessingRequest.Merge(dst, src)
}
func (m *ProcessingRequest) XXX_Size() int {
	return xxx_messageInfo_ProcessingRequest.Size(m)
}
func (m *ProcessingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ProcessingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ProcessingRequest proto.InternalMessageInfo

func (m *ProcessingRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ProcessingRequest) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *ProcessingRequest) GetIntentId() string {
	if m != nil {
		return m.IntentId
	}
	return ""
}

func (m *ProcessingRequest) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

func (m *ProcessingRequest) GetChannelId() string {
	if m != nil {
		return m.ChannelId
	}
	return ""
}

func (m *ProcessingRequest) GetServerId() string {
	if m != nil {
		return m.ServerId
	}
	return ""
}

func (m *ProcessingRequest) GetBotId() string {
	if m != nil {
		return m.BotId
	}
	return ""
}

func (m *ProcessingRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *ProcessingRequest) GetCreated() int64 {
	if m != nil {
		return m.Created
	}
	return 0
}

type ProcessingEvent struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ProcessingRequestId  string   `protobuf:"bytes,2,opt,name=processingRequestId,proto3" json:"processingRequestId,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Type                 string   `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	Created              int64    `protobuf:"varint,5,opt,name=created,proto3" json:"created,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProcessingEvent) Reset()         { *m = ProcessingEvent{} }
func (m *ProcessingEvent) String() string { return proto.CompactTextString(m) }
func (*ProcessingEvent) ProtoMessage()    {}
func (*ProcessingEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_processing_41c2f33854a863ab, []int{9}
}
func (m *ProcessingEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProcessingEvent.Unmarshal(m, b)
}
func (m *ProcessingEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProcessingEvent.Marshal(b, m, deterministic)
}
func (dst *ProcessingEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProcessingEvent.Merge(dst, src)
}
func (m *ProcessingEvent) XXX_Size() int {
	return xxx_messageInfo_ProcessingEvent.Size(m)
}
func (m *ProcessingEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_ProcessingEvent.DiscardUnknown(m)
}

var xxx_messageInfo_ProcessingEvent proto.InternalMessageInfo

func (m *ProcessingEvent) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ProcessingEvent) GetProcessingRequestId() string {
	if m != nil {
		return m.ProcessingRequestId
	}
	return ""
}

func (m *ProcessingEvent) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *ProcessingEvent) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *ProcessingEvent) GetCreated() int64 {
	if m != nil {
		return m.Created
	}
	return 0
}

type ProcessingRequestIntentStatisticsRequest struct {
	ServerId                    string   `protobuf:"bytes,1,opt,name=serverId,proto3" json:"serverId,omitempty"`
	IntentId                    string   `protobuf:"bytes,2,opt,name=intentId,proto3" json:"intentId,omitempty"`
	UserId                      string   `protobuf:"bytes,3,opt,name=userId,proto3" json:"userId,omitempty"`
	Type                        string   `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	CreatedGreaterThanOrEqualTo int64    `protobuf:"varint,5,opt,name=createdGreaterThanOrEqualTo,proto3" json:"createdGreaterThanOrEqualTo,omitempty"`
	CreatedLessThanOrEqualTo    int64    `protobuf:"varint,6,opt,name=createdLessThanOrEqualTo,proto3" json:"createdLessThanOrEqualTo,omitempty"`
	UserLimit                   int32    `protobuf:"varint,7,opt,name=userLimit,proto3" json:"userLimit,omitempty"`
	XXX_NoUnkeyedLiteral        struct{} `json:"-"`
	XXX_unrecognized            []byte   `json:"-"`
	XXX_sizecache               int32    `json:"-"`
}

func (m *ProcessingRequestIntentStatisticsRequest) Reset() {
	*m = ProcessingRequestIntentStatisticsRequest{}
}
func (m *ProcessingRequestIntentStatisticsRequest) String() string { return proto.CompactTextString(m) }
func (*ProcessingRequestIntentStatisticsRequest) ProtoMessage()    {}
func (*ProcessingRequestIntentStatisticsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_processing_41c2f33854a863ab, []int{10}
}
func (m *ProcessingRequestIntentStatisticsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProcessingRequestIntentStatisticsRequest.Unmarshal(m, b)
}
func (m *ProcessingRequestIntentStatisticsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProcessingRequestIntentStatisticsRequest.Marshal(b, m, deterministic)
}
func (dst *ProcessingRequestIntentStatisticsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProcessingRequestIntentStatisticsRequest.Merge(dst, src)
}
func (m *ProcessingRequestIntentStatisticsRequest) XXX_Size() int {
	return xxx_messageInfo_ProcessingRequestIntentStatisticsRequest.Size(m)
}
func (m *ProcessingRequestIntentStatisticsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ProcessingRequestIntentStatisticsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ProcessingRequestIntentStatisticsRequest proto.InternalMessageInfo

func (m *ProcessingRequestIntentStatisticsRequest) GetServerId() string {
	if m != nil {
		return m.ServerId
	}
	return ""
}

func (m *ProcessingRequestIntentStatisticsRequest) GetIntentId() string {
	if m != nil {
		return m.IntentId
	}
	return ""
}

func (m *ProcessingRequestIntentStatisticsRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *ProcessingRequestIntentStatisticsRequest) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *ProcessingRequestIntentStatisticsRequest) GetCreatedGreaterThanOrEqualTo() int64 {
	if m != nil {
		return m.CreatedGreaterThanOrEqualTo
	}
	return 0
}

func (m *ProcessingRequestIntentStatisticsRequest) GetCreatedLessThanOrEqualTo() int64 {
	if m != nil {
		return m.CreatedLessThanOrEqualTo
	}
	return 0
}

func (m *ProcessingRequestIntentStatisticsRequest) GetUserLimit() int32 {
	if m != nil {
		return m.UserLimit
	}
	return 0
}

type ProcessingRequestIntentStatisticsReply struct {
	IntentId             string           `protobuf:"bytes,1,opt,name=intentId,proto3" json:"intentId,omitempty"`
	UserStatistics       []*UserStatistic `protobuf:"bytes,2,rep,name=userStatistics,proto3" json:"userStatistics,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *ProcessingRequestIntentStatisticsReply) Reset() {
	*m = ProcessingRequestIntentStatisticsReply{}
}
func (m *ProcessingRequestIntentStatisticsReply) String() string { return proto.CompactTextString(m) }
func (*ProcessingRequestIntentStatisticsReply) ProtoMessage()    {}
func (*ProcessingRequestIntentStatisticsReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_processing_41c2f33854a863ab, []int{11}
}
func (m *ProcessingRequestIntentStatisticsReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProcessingRequestIntentStatisticsReply.Unmarshal(m, b)
}
func (m *ProcessingRequestIntentStatisticsReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProcessingRequestIntentStatisticsReply.Marshal(b, m, deterministic)
}
func (dst *ProcessingRequestIntentStatisticsReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProcessingRequestIntentStatisticsReply.Merge(dst, src)
}
func (m *ProcessingRequestIntentStatisticsReply) XXX_Size() int {
	return xxx_messageInfo_ProcessingRequestIntentStatisticsReply.Size(m)
}
func (m *ProcessingRequestIntentStatisticsReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ProcessingRequestIntentStatisticsReply.DiscardUnknown(m)
}

var xxx_messageInfo_ProcessingRequestIntentStatisticsReply proto.InternalMessageInfo

func (m *ProcessingRequestIntentStatisticsReply) GetIntentId() string {
	if m != nil {
		return m.IntentId
	}
	return ""
}

func (m *ProcessingRequestIntentStatisticsReply) GetUserStatistics() []*UserStatistic {
	if m != nil {
		return m.UserStatistics
	}
	return nil
}

type UserStatistic struct {
	UserId               string   `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Count                int64    `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserStatistic) Reset()         { *m = UserStatistic{} }
func (m *UserStatistic) String() string { return proto.CompactTextString(m) }
func (*UserStatistic) ProtoMessage()    {}
func (*UserStatistic) Descriptor() ([]byte, []int) {
	return fileDescriptor_processing_41c2f33854a863ab, []int{12}
}
func (m *UserStatistic) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserStatistic.Unmarshal(m, b)
}
func (m *UserStatistic) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserStatistic.Marshal(b, m, deterministic)
}
func (dst *UserStatistic) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserStatistic.Merge(dst, src)
}
func (m *UserStatistic) XXX_Size() int {
	return xxx_messageInfo_UserStatistic.Size(m)
}
func (m *UserStatistic) XXX_DiscardUnknown() {
	xxx_messageInfo_UserStatistic.DiscardUnknown(m)
}

var xxx_messageInfo_UserStatistic proto.InternalMessageInfo

func (m *UserStatistic) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *UserStatistic) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

type SendProcessingEventReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendProcessingEventReply) Reset()         { *m = SendProcessingEventReply{} }
func (m *SendProcessingEventReply) String() string { return proto.CompactTextString(m) }
func (*SendProcessingEventReply) ProtoMessage()    {}
func (*SendProcessingEventReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_processing_41c2f33854a863ab, []int{13}
}
func (m *SendProcessingEventReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendProcessingEventReply.Unmarshal(m, b)
}
func (m *SendProcessingEventReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendProcessingEventReply.Marshal(b, m, deterministic)
}
func (dst *SendProcessingEventReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendProcessingEventReply.Merge(dst, src)
}
func (m *SendProcessingEventReply) XXX_Size() int {
	return xxx_messageInfo_SendProcessingEventReply.Size(m)
}
func (m *SendProcessingEventReply) XXX_DiscardUnknown() {
	xxx_messageInfo_SendProcessingEventReply.DiscardUnknown(m)
}

var xxx_messageInfo_SendProcessingEventReply proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MessageReplyReceived)(nil), "processingpb.MessageReplyReceived")
	proto.RegisterType((*MessageRequest)(nil), "processingpb.MessageRequest")
	proto.RegisterType((*User)(nil), "processingpb.User")
	proto.RegisterType((*Server)(nil), "processingpb.Server")
	proto.RegisterType((*Response)(nil), "processingpb.Response")
	proto.RegisterType((*SendMessageRequestReply)(nil), "processingpb.SendMessageRequestReply")
	proto.RegisterType((*MessageReplyRequest)(nil), "processingpb.MessageReplyRequest")
	proto.RegisterType((*MessageReply)(nil), "processingpb.MessageReply")
	proto.RegisterType((*ProcessingRequest)(nil), "processingpb.ProcessingRequest")
	proto.RegisterType((*ProcessingEvent)(nil), "processingpb.ProcessingEvent")
	proto.RegisterType((*ProcessingRequestIntentStatisticsRequest)(nil), "processingpb.ProcessingRequestIntentStatisticsRequest")
	proto.RegisterType((*ProcessingRequestIntentStatisticsReply)(nil), "processingpb.ProcessingRequestIntentStatisticsReply")
	proto.RegisterType((*UserStatistic)(nil), "processingpb.UserStatistic")
	proto.RegisterType((*SendProcessingEventReply)(nil), "processingpb.SendProcessingEventReply")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ProcessingClient is the client API for Processing service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ProcessingClient interface {
	SendMessageRequest(ctx context.Context, in *MessageRequest, opts ...grpc.CallOption) (*SendMessageRequestReply, error)
	GetMessageReply(ctx context.Context, in *MessageReplyRequest, opts ...grpc.CallOption) (*MessageReply, error)
	SendProcessingEvent(ctx context.Context, in *ProcessingEvent, opts ...grpc.CallOption) (*SendProcessingEventReply, error)
	ProcessingRequestIntentStatistics(ctx context.Context, in *ProcessingRequestIntentStatisticsRequest, opts ...grpc.CallOption) (*ProcessingRequestIntentStatisticsReply, error)
}

type processingClient struct {
	cc *grpc.ClientConn
}

func NewProcessingClient(cc *grpc.ClientConn) ProcessingClient {
	return &processingClient{cc}
}

func (c *processingClient) SendMessageRequest(ctx context.Context, in *MessageRequest, opts ...grpc.CallOption) (*SendMessageRequestReply, error) {
	out := new(SendMessageRequestReply)
	err := c.cc.Invoke(ctx, "/processingpb.Processing/SendMessageRequest", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *processingClient) GetMessageReply(ctx context.Context, in *MessageReplyRequest, opts ...grpc.CallOption) (*MessageReply, error) {
	out := new(MessageReply)
	err := c.cc.Invoke(ctx, "/processingpb.Processing/GetMessageReply", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *processingClient) SendProcessingEvent(ctx context.Context, in *ProcessingEvent, opts ...grpc.CallOption) (*SendProcessingEventReply, error) {
	out := new(SendProcessingEventReply)
	err := c.cc.Invoke(ctx, "/processingpb.Processing/SendProcessingEvent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *processingClient) ProcessingRequestIntentStatistics(ctx context.Context, in *ProcessingRequestIntentStatisticsRequest, opts ...grpc.CallOption) (*ProcessingRequestIntentStatisticsReply, error) {
	out := new(ProcessingRequestIntentStatisticsReply)
	err := c.cc.Invoke(ctx, "/processingpb.Processing/ProcessingRequestIntentStatistics", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProcessingServer is the server API for Processing service.
type ProcessingServer interface {
	SendMessageRequest(context.Context, *MessageRequest) (*SendMessageRequestReply, error)
	GetMessageReply(context.Context, *MessageReplyRequest) (*MessageReply, error)
	SendProcessingEvent(context.Context, *ProcessingEvent) (*SendProcessingEventReply, error)
	ProcessingRequestIntentStatistics(context.Context, *ProcessingRequestIntentStatisticsRequest) (*ProcessingRequestIntentStatisticsReply, error)
}

func RegisterProcessingServer(s *grpc.Server, srv ProcessingServer) {
	s.RegisterService(&_Processing_serviceDesc, srv)
}

func _Processing_SendMessageRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProcessingServer).SendMessageRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/processingpb.Processing/SendMessageRequest",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProcessingServer).SendMessageRequest(ctx, req.(*MessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Processing_GetMessageReply_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MessageReplyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProcessingServer).GetMessageReply(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/processingpb.Processing/GetMessageReply",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProcessingServer).GetMessageReply(ctx, req.(*MessageReplyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Processing_SendProcessingEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProcessingEvent)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProcessingServer).SendProcessingEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/processingpb.Processing/SendProcessingEvent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProcessingServer).SendProcessingEvent(ctx, req.(*ProcessingEvent))
	}
	return interceptor(ctx, in, info, handler)
}

func _Processing_ProcessingRequestIntentStatistics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProcessingRequestIntentStatisticsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProcessingServer).ProcessingRequestIntentStatistics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/processingpb.Processing/ProcessingRequestIntentStatistics",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProcessingServer).ProcessingRequestIntentStatistics(ctx, req.(*ProcessingRequestIntentStatisticsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Processing_serviceDesc = grpc.ServiceDesc{
	ServiceName: "processingpb.Processing",
	HandlerType: (*ProcessingServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendMessageRequest",
			Handler:    _Processing_SendMessageRequest_Handler,
		},
		{
			MethodName: "GetMessageReply",
			Handler:    _Processing_GetMessageReply_Handler,
		},
		{
			MethodName: "SendProcessingEvent",
			Handler:    _Processing_SendProcessingEvent_Handler,
		},
		{
			MethodName: "ProcessingRequestIntentStatistics",
			Handler:    _Processing_ProcessingRequestIntentStatistics_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "processing.proto",
}

func init() { proto.RegisterFile("processing.proto", fileDescriptor_processing_41c2f33854a863ab) }

var fileDescriptor_processing_41c2f33854a863ab = []byte{
	// 738 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x56, 0xcd, 0x6a, 0xdc, 0x3c,
	0x14, 0x8d, 0xc7, 0xf3, 0x7b, 0xf3, 0xf7, 0x7d, 0xca, 0x90, 0x0a, 0x27, 0x85, 0x89, 0x48, 0x86,
	0x69, 0x29, 0x43, 0x49, 0x4b, 0x17, 0x85, 0x42, 0xa1, 0x84, 0x30, 0x90, 0xd2, 0xe0, 0xa4, 0xab,
	0x42, 0xc1, 0x63, 0x8b, 0xc4, 0x90, 0x91, 0x1c, 0x4b, 0x13, 0xc8, 0x23, 0x74, 0xdd, 0x47, 0xe8,
	0xae, 0xdb, 0xee, 0xba, 0xe8, 0x1b, 0xf5, 0x1d, 0x8a, 0x64, 0x8f, 0x6d, 0xd9, 0x9e, 0x34, 0x6d,
	0x57, 0xf1, 0xd5, 0x3d, 0xd2, 0x3d, 0x3a, 0xf7, 0xe8, 0x66, 0xe0, 0xbf, 0x28, 0xe6, 0x3e, 0x15,
	0x22, 0x64, 0x17, 0xe3, 0x28, 0xe6, 0x92, 0xa3, 0xb5, 0x7c, 0x25, 0x9a, 0x92, 0x21, 0xf4, 0xdf,
	0x52, 0x21, 0xbc, 0x0b, 0xea, 0xd2, 0xe8, 0xea, 0xd6, 0xa5, 0x3e, 0x0d, 0x6f, 0x68, 0x80, 0x36,
	0xa0, 0x31, 0x09, 0xb0, 0x35, 0xb0, 0x46, 0x3d, 0xb7, 0x31, 0x09, 0xc8, 0x8f, 0x06, 0x6c, 0x64,
	0xc0, 0xeb, 0x39, 0x15, 0x52, 0x41, 0xc2, 0x0c, 0x12, 0x06, 0x68, 0x1b, 0xda, 0x82, 0xcf, 0x63,
	0x9f, 0xe2, 0x86, 0x5e, 0x4b, 0x23, 0xb4, 0x0f, 0xf6, 0x94, 0x4b, 0x6c, 0x0f, 0xac, 0xd1, 0xea,
	0x21, 0x1a, 0x17, 0xcb, 0x8f, 0xdf, 0x0b, 0x1a, 0xbb, 0x2a, 0x8d, 0x1e, 0x43, 0xdb, 0x9b, 0xcb,
	0x4b, 0x1e, 0xe3, 0xe6, 0x52, 0x60, 0x8a, 0x40, 0xbb, 0xd0, 0xf3, 0x2f, 0x3d, 0xc6, 0xe8, 0xd5,
	0x24, 0xc0, 0x2d, 0x5d, 0x2c, 0x5f, 0x40, 0x0e, 0x74, 0x05, 0x8d, 0x6f, 0x68, 0x3c, 0x09, 0x70,
	0x5b, 0x27, 0xb3, 0x18, 0x8d, 0xa1, 0x93, 0x7c, 0x0b, 0xdc, 0x19, 0xd8, 0xa3, 0xd5, 0xc3, 0xbe,
	0x59, 0xe6, 0x4c, 0x27, 0xdd, 0x05, 0x08, 0x8d, 0xa1, 0x3b, 0xa3, 0x4c, 0x86, 0x9c, 0x09, 0xdc,
	0xd5, 0x1b, 0xea, 0x78, 0x65, 0x18, 0x84, 0xa1, 0xe3, 0x73, 0x26, 0x29, 0x93, 0xb8, 0xa7, 0x4b,
	0x2f, 0x42, 0x72, 0x0a, 0x4d, 0x85, 0xad, 0xa8, 0x86, 0xa0, 0xc9, 0xbc, 0xd9, 0x42, 0x33, 0xfd,
	0x8d, 0xf6, 0x61, 0x3d, 0x08, 0x85, 0x1f, 0x87, 0xb3, 0x90, 0x79, 0x92, 0xc7, 0x5a, 0xbb, 0x9e,
	0x6b, 0x2e, 0x92, 0x27, 0xd0, 0x4e, 0xe8, 0xde, 0xe7, 0x4c, 0x32, 0x84, 0xae, 0x4b, 0x45, 0xc4,
	0x99, 0xa0, 0x4a, 0xa1, 0x59, 0xd2, 0x4b, 0x81, 0xad, 0x81, 0xad, 0x14, 0x5a, 0xc4, 0xe4, 0x11,
	0x3c, 0x38, 0xa3, 0x2c, 0x30, 0x7b, 0xad, 0xbd, 0x51, 0x2e, 0x43, 0x0e, 0x60, 0xcb, 0xf4, 0x4e,
	0xad, 0x2f, 0xc8, 0x77, 0x0b, 0xd6, 0x8a, 0xb8, 0x0a, 0xdd, 0xa7, 0xb0, 0x95, 0x6b, 0x9a, 0x9e,
	0x32, 0x09, 0x52, 0xf6, 0x75, 0x29, 0xd3, 0x00, 0x76, 0xd9, 0x00, 0xdb, 0xd0, 0x9e, 0x0b, 0xdd,
	0xfe, 0x66, 0x62, 0xc4, 0x24, 0x2a, 0x36, 0xa7, 0x65, 0x34, 0x47, 0x67, 0x62, 0xea, 0x49, 0x9a,
	0x38, 0xc6, 0x76, 0x17, 0x21, 0xf9, 0x69, 0xc1, 0xff, 0xa7, 0x65, 0x06, 0x75, 0x82, 0xcb, 0xdb,
	0x28, 0x13, 0x5c, 0x7d, 0x2b, 0x91, 0x43, 0x7d, 0x7a, 0x46, 0x31, 0x8b, 0x0b, 0x4f, 0xa5, 0x69,
	0x3c, 0x95, 0xbf, 0x37, 0x76, 0x1f, 0x5a, 0x53, 0xae, 0x4a, 0x75, 0x74, 0x22, 0x09, 0x0a, 0x4a,
	0x74, 0x2b, 0x4a, 0xa4, 0xf7, 0xed, 0x99, 0xf7, 0xfd, 0x62, 0xc1, 0x66, 0x7e, 0xdf, 0xa3, 0x1b,
	0xa5, 0xce, 0xbf, 0xf7, 0x6b, 0x00, 0xab, 0x01, 0x55, 0xde, 0x8d, 0xd4, 0x33, 0x49, 0xe5, 0x28,
	0x2e, 0x65, 0x0a, 0x36, 0x0b, 0x0a, 0x16, 0x58, 0xb6, 0x4c, 0x96, 0x5f, 0x1b, 0x30, 0xaa, 0x74,
	0x65, 0xa2, 0xd5, 0x3d, 0x93, 0x9e, 0x0c, 0x85, 0x0c, 0x7d, 0xb1, 0x68, 0x56, 0x51, 0x36, 0xab,
	0x24, 0x5b, 0xb1, 0x49, 0x8d, 0x6a, 0x93, 0x52, 0xf1, 0x6c, 0x43, 0xbc, 0x3a, 0xaa, 0xaf, 0x61,
	0x27, 0xe5, 0x76, 0xac, 0xff, 0xc4, 0xe7, 0x97, 0x1e, 0x7b, 0x17, 0x1f, 0x5d, 0xcf, 0xbd, 0xab,
	0x73, 0x9e, 0xd2, 0xbf, 0x0b, 0x82, 0x5e, 0x02, 0x4e, 0xd3, 0x27, 0x54, 0x08, 0x73, 0x7b, 0xe2,
	0xc9, 0xa5, 0x79, 0x65, 0x1b, 0xc5, 0xed, 0x24, 0x9c, 0x85, 0x52, 0x1b, 0xa0, 0xe5, 0xe6, 0x0b,
	0xe4, 0x93, 0x05, 0xc3, 0x7b, 0x88, 0xa5, 0x5e, 0x66, 0x51, 0x0e, 0xab, 0x24, 0xc7, 0x1b, 0xd8,
	0x50, 0x67, 0xe6, 0x5b, 0x70, 0x43, 0x0f, 0xc4, 0x9d, 0xea, 0x40, 0xcc, 0x30, 0x6e, 0x69, 0x0b,
	0x79, 0x05, 0xeb, 0x06, 0xa0, 0x20, 0xb2, 0x65, 0x88, 0xdc, 0x87, 0x96, 0xcf, 0xe7, 0x4c, 0xea,
	0xae, 0xd8, 0x6e, 0x12, 0x10, 0x07, 0xb0, 0x1a, 0x4e, 0x25, 0x83, 0x6a, 0xee, 0x87, 0xdf, 0x6c,
	0x80, 0x3c, 0x81, 0x3e, 0x00, 0xaa, 0xce, 0x31, 0xb4, 0x6b, 0x92, 0x35, 0xb3, 0xce, 0x41, 0xf9,
	0x9f, 0x41, 0xed, 0x1c, 0x24, 0x2b, 0xc8, 0x85, 0xcd, 0x63, 0x2a, 0x8d, 0xa1, 0xb6, 0xb7, 0xe4,
	0xe4, 0x7c, 0x30, 0x3a, 0xce, 0x72, 0x08, 0x59, 0x41, 0x1f, 0x61, 0xab, 0xe6, 0x6e, 0xe8, 0xa1,
	0xb9, 0xa9, 0x94, 0x76, 0x86, 0x55, 0xca, 0x75, 0xea, 0x90, 0x15, 0xf4, 0xd9, 0x82, 0xbd, 0xdf,
	0xda, 0x00, 0xbd, 0x58, 0x56, 0xee, 0xee, 0x47, 0xe6, 0x3c, 0xff, 0xe3, 0x7d, 0x9a, 0xd5, 0xb4,
	0xad, 0x7f, 0x94, 0x3c, 0xfb, 0x15, 0x00, 0x00, 0xff, 0xff, 0xc9, 0x18, 0xda, 0x8d, 0xa8, 0x08,
	0x00, 0x00,
}
