version: 2
jobs:
  build:
    docker:
      - image: golang:1.11
    working_directory: /go/src/github.com/jukeizu/treediagram
    steps:
      - checkout
      - restore_cache:
          keys:
            - pkg-sum-{{ checksum "go.sum" }}
      - run: make
      - save_cache:
          key: pkg-sum-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg"
